apiVersion: apps/v1
kind: Deployment
metadata:
  name: demokeyvault-deployment
  labels:
    app: demokeyvault
spec:
  replicas: 1
  template:
    metadata:
      name: demokeyvault
      labels:
        app: demokeyvault
    spec:
      containers:
        - name: demokeyvault
          image: commonregistryacr.azurecr.io/keyvault-demo:v2
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: demokeyvault


---

apiVersion: v1
kind: Service
metadata:
  name: demokeyvault-svc
spec:
  selector:
    app: demokeyvault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

